# Generated by Django 6.0.1 on 2026-01-13 16:24

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Habilidad')),
                ('nivel', models.PositiveIntegerField(help_text='Nivel de 1 a 100', verbose_name='Nivel')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo Proyecto')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('tecnologias', models.CharField(help_text='Ej: Django, PostgeSQL, Pandas, Python, PowerBI', max_length=255, verbose_name='Tecnologias Usadas')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos', verbose_name='Imagen')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url Proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('tipo_servicio', models.CharField(choices=[('web', 'Desarrollo Web'), ('ecommerce', 'E-commerce / Tiendas Online'), ('automation', 'Automatizaciones'), ('data', 'Análisis de Datos'), ('software', 'Software a Medida')], max_length=20, verbose_name='Tipo de Servicio')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('icon', models.CharField(help_text='Ej: fa-solid fa-code', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Servicio Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id'],
            },
        ),
    ]
